#!/bin/sh

set -e

# Any option is described with `lb config -h`

# Necessary for build process
ARCHIVES="main non-free-firmware"
DISTRO=bookworm
BOOTLOADER=grub-pc
CACHE_PACKAGES=true

# General info
USERNAME=live-cd
HOSTNAME=sos-live-cd

# Interactive mode (shell or false)
SHELL=shell

# ISO info
IMAGE_NAME="Online-SOS-livecd"
ISO_APP="Online-SOS LiveCD"
ISO_VER="SOS - 0.1 - Build"
ISO_PUBLISHER="SOS"
ISO_VOLUME="sos_livecd"

# Network settings
DRIVE_INTERFACE="eth33"
MODE="dhcp"
FORMATTED_IP=":::::$DRIVE_INTERFACE:$MODE"

## Example: Static address
#DRIVE_INTERFACE="eth33"
#IP="1.1.1.1"
#NETMASK="255.255.255.0"
#GW="1.1.1.254"
#FORMATTED_IP="$DRIVE_INTERFACE:$IP:$NETMASK:$GW:$HOSTNAME:"

lb config noauto \
	--archive-areas "$ARCHIVES" \
	--parent-archive-areas "$ARCHIVES" \
	--distribution "$DISTRO" \
	--distribution-binary "$DISTRO" \
	--distribution-chroot "$DISTRO" \
	--parent-distribution "$DISTRO" \
	--parent-distribution-binary "$DISTRO" \
	--parent-distribution-chroot "$DISTRO" \
	--bootloader "$BOOTLOADER" \
	--image-name $IMAGE_NAME \
	--iso-application $ISO_APP \
	--iso-preparer $ISO_VER \
	--iso-publisher $ISO_PUBLISHER \
	--iso-volume $ISO_VOLUME \
	--interactive $SHELL \
	--cache-packages $CACHE_PACKAGES \
	--bootappend-live "boot=live components quiet splash\
 username=$USERNAME\
 hostname=$HOSTNAME\
 ip=$FORMATTED_IP" \
	--clean \
	--color \
	--debug \
	--verbose \
	"${@}"