#!/bin/sh

set -e

# Any option is described with `lb config -h`

# Necessary for build process
ARCHIVES="main non-free-firmware"
DISTRO=bookworm
BOOTLOADER=grub-pc
CACHE_PACKAGES=false # No need to cache if you run local-repo on your build host

# General info
USERNAME=of-live-cd
HOSTNAME=sos-of-live-cd

# Interactive mode (shell or false)
SHELL=false

# ISO info
IMAGE_NAME="Offline-SOS-livecd"
ISO_APP="Offline-SOS LiveCD"
ISO_VER="SOS - 0.1 - Build"
ISO_PUBLISHER="SOS"
ISO_VOLUME="off_sos_livecd"

# Network settings
DRIVE_INTERFACE="ens33"
IP="1.1.1.1"
NETMASK="255.255.255.0"
GW="1.1.1.254"
FORMATTED_IP="ip=$DRIVE_INTERFACE:$IP:$NETMASK:$GW:$HOSTNAME:"

## Example: dhcp
#FORMATTED_IP=""

# Local repo info [Defaults to network settings]
LOCAL_IP=192.168.183.133 #IP of your offline environment
MIRROR_BOOTSTRAP="http://$LOCAL_IP:8000"
MIRROR_URL="[trusted=yes] $MIRROR_BOOTSTRAP"

lb config noauto \
	--archive-areas "$ARCHIVES" \
	--parent-archive-areas "$ARCHIVES" \
	--distribution "$DISTRO" \
	--distribution-binary "$DISTRO" \
	--distribution-chroot "$DISTRO" \
	--parent-distribution "$DISTRO" \
	--parent-distribution-binary "$DISTRO" \
	--parent-distribution-chroot "$DISTRO" \
	--mirror-binary "$MIRROR_URL" \
	--mirror-bootstrap "$MIRROR_BOOTSTRAP" \
	--mirror-chroot "$MIRROR_URL" \ \
	--parent-mirror-binary "$MIRROR_URL" \
	--parent-mirror-bootstrap "$MIRROR_BOOTSTRAP" \
	--parent-mirror-chroot "$MIRROR_URL" \
	--apt-secure false \
	--cache-packages false \
	--security false \
	--updates false \
	--firmware-chroot false \
	--firmware-binary false \
	--bootloader "$BOOTLOADER" \
	--image-name $IMAGE_NAME \
	--iso-application $ISO_APP \
	--iso-preparer $ISO_VER \
	--iso-publisher $ISO_PUBLISHER \
	--iso-volume $ISO_VOLUME \
	--interactive $SHELL \
	--cache-packages $CACHE_PACKAGES \
	--bootappend-live "boot=live components quiet splash\
 username=$USERNAME\
 hostname=$HOSTNAME\
 $FORMATTED_IP" \
	--clean \
	--color \
	--debug \
	--verbose \
	"${@}"
